//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CM_Account
    {
        public int ID { get; set; }
        public Nullable<int> BatchReferenceID { get; set; }
        public Nullable<int> RegistyOfDeedsId { get; set; }
        public string AccountName { get; set; }
        public string EngineNo { get; set; }
        public string RDORNo { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string EpebNo { get; set; }
        public Nullable<decimal> LoadAmount { get; set; }
        public Nullable<decimal> RequestedRDFee { get; set; }
        public Nullable<decimal> RDFee { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public Nullable<decimal> GratuityFee { get; set; }
        public Nullable<decimal> MCAmount { get; set; }
        public Nullable<int> StaffInChargeId { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsProcessing { get; set; }
    }
}
