//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CM_ReleasedMain_Report
    {
        public int id { get; set; }
        public string AccountName { get; set; }
        public string EngineNo { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string EpebNo { get; set; }
        public string RegistryOfDeeds { get; set; }
        public string BankLad { get; set; }
        public Nullable<int> BankId { get; set; }
    }
}
