//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CM_BudgetRequestEntry
    {
        public int ID { get; set; }
        public Nullable<int> budgetrequestid { get; set; }
        public Nullable<int> accountid { get; set; }
        public Nullable<decimal> loadamount { get; set; }
        public Nullable<decimal> requestedrdfee { get; set; }
    }
}
