//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CM_TransmittalBatch_Report
    {
        public int id { get; set; }
        public string transmittalbatch { get; set; }
        public Nullable<int> accountid { get; set; }
        public string AccountName { get; set; }
        public string registryofdeedsname { get; set; }
        public Nullable<int> doccopy { get; set; }
        public string EpebNo { get; set; }
        public string recievedbyname { get; set; }
    }
}
