//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CM_BudgetRequestBatch_Report
    {
        public int id { get; set; }
        public string budgetrequestid { get; set; }
        public string RegistryOfDeedsDescription { get; set; }
        public Nullable<System.DateTime> daterecieved { get; set; }
        public decimal requestedbudget { get; set; }
        public Nullable<decimal> LoadAmount { get; set; }
        public Nullable<decimal> RequestedRDFee { get; set; }
        public Nullable<decimal> RDFee { get; set; }
        public Nullable<decimal> budgetrequestgrandtotal { get; set; }
        public string staffinchargename { get; set; }
        public string checkedbyname { get; set; }
        public string approvedbyname { get; set; }
    }
}
