//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_CM_Account_Logs
    {
        public int id { get; set; }
        public Nullable<int> accointid { get; set; }
        public string logdescription { get; set; }
        public Nullable<System.DateTime> dateencoded { get; set; }
        public Nullable<int> encodedby { get; set; }
    }
}
