//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_ForConfirmationReplyBatch_Report
    {
        public int id { get; set; }
        public string forconfirmationreplybatch { get; set; }
        public string FieldOfficeName { get; set; }
        public Nullable<System.DateTime> daterecieved { get; set; }
        public string CheckedByName { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<decimal> requestedltofeereply { get; set; }
    }
}
