//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_ForEncumbranceBatch_Report
    {
        public int id { get; set; }
        public string encumbrancebatch { get; set; }
        public string FieldOfficeName { get; set; }
        public Nullable<System.DateTime> targetdate { get; set; }
        public string checkedbyname { get; set; }
        public string ApproveByName { get; set; }
        public string regionaldirectorname { get; set; }
        public Nullable<decimal> requestedltofeeencumbrance { get; set; }
        public string AgencyName { get; set; }
    }
}
