//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_TransmittalBatch_Report
    {
        public int id { get; set; }
        public string transmittalbatch { get; set; }
        public string LadName { get; set; }
        public Nullable<System.DateTime> dateencoded { get; set; }
        public string recievedbyname { get; set; }
        public string accountname { get; set; }
        public string crno { get; set; }
        public string rdorno { get; set; }
        public string agencyname { get; set; }
    }
}
