//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_ForEncumbranceLTO_Report
    {
        public Nullable<int> encumbranceid { get; set; }
        public Nullable<System.DateTime> targetdate { get; set; }
        public int id { get; set; }
        public string accountname { get; set; }
        public string make { get; set; }
        public string series { get; set; }
        public string OfficerInChargeName { get; set; }
        public string regionaldirectorname { get; set; }
        public Nullable<System.DateTime> daterecieved { get; set; }
        public string mvfileno { get; set; }
    }
}
