//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_Account
    {
        public int id { get; set; }
        public Nullable<int> batchreferenceno { get; set; }
        public string accountname { get; set; }
        public string mvfileno { get; set; }
        public string engineno { get; set; }
        public Nullable<int> ltofieldofficeid { get; set; }
        public Nullable<int> ltoaddressid { get; set; }
        public Nullable<int> ltoagencyid { get; set; }
        public Nullable<decimal> gratuityfee { get; set; }
        public Nullable<decimal> requestedltofeeconfirmation { get; set; }
        public Nullable<decimal> requestedltofeereply { get; set; }
        public Nullable<decimal> requestedltofeeencumbrance { get; set; }
        public Nullable<decimal> ltofee { get; set; }
        public Nullable<decimal> servicefee { get; set; }
        public string crno { get; set; }
        public Nullable<System.DateTime> dateofentry { get; set; }
        public string rdorno { get; set; }
        public Nullable<int> staffinchargeid { get; set; }
        public Nullable<bool> isprocessing { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<bool> isreturn { get; set; }
    }
}
