//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_BillingMain_Report
    {
        public Nullable<int> billingcount { get; set; }
        public int id { get; set; }
        public Nullable<int> transmittalid { get; set; }
        public Nullable<int> LadName { get; set; }
        public Nullable<System.DateTime> billingdate { get; set; }
        public string contactpersonname { get; set; }
        public string preparedbyname { get; set; }
        public string checkedbyname { get; set; }
        public string approvedbyname { get; set; }
        public Nullable<int> billingnumber { get; set; }
    }
}
