//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_LTO_ForConfirmationReplyBatch
    {
        public int id { get; set; }
        public string forconfirmationreplybatch { get; set; }
        public Nullable<int> fieldofficeid { get; set; }
        public Nullable<System.DateTime> targetdate { get; set; }
        public Nullable<System.DateTime> daterecieved { get; set; }
        public Nullable<int> staffinchargeid { get; set; }
        public Nullable<int> checkedbyid { get; set; }
        public Nullable<int> approvedbyid { get; set; }
        public Nullable<int> approvalstatus { get; set; }
        public Nullable<int> EncodedById { get; set; }
        public Nullable<System.DateTime> dateencoded { get; set; }
    }
}
