//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_BillingBatch
    {
        public int id { get; set; }
        public Nullable<int> transmittalid { get; set; }
        public Nullable<int> bankid { get; set; }
        public Nullable<System.DateTime> billingdate { get; set; }
        public string contactperson { get; set; }
        public Nullable<int> preparedbyid { get; set; }
        public Nullable<int> checkedbyid { get; set; }
        public Nullable<int> approvedbyid { get; set; }
        public Nullable<int> approvalstatusid { get; set; }
        public Nullable<System.DateTime> dateencoded { get; set; }
        public Nullable<int> encodedbyid { get; set; }
        public Nullable<int> billingnumber { get; set; }
    }
}
