//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_CTC_BillingSub_Report
    {
        public Nullable<int> billingbatch { get; set; }
        public Nullable<int> accountid { get; set; }
        public Nullable<decimal> rdregfee { get; set; }
        public string tctno { get; set; }
        public int id { get; set; }
        public string accountname { get; set; }
    }
}
