//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_BudgetRequestEntry_Report
    {
        public Nullable<int> budgetrequestid { get; set; }
        public int ID { get; set; }
        public string accountname { get; set; }
        public Nullable<decimal> loanamount { get; set; }
        public decimal RequestedRDFee { get; set; }
        public decimal RDFee { get; set; }
        public decimal diff { get; set; }
        public decimal gratuityfee { get; set; }
    }
}
