//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_AccountListOfDocument
    {
        public int ID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<int> ContactPerson { get; set; }
        public string Comment { get; set; }
    }
}
