//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_BillingCMAnnotation_Report
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> accountid { get; set; }
        public string accountname { get; set; }
        public string RDVenue { get; set; }
        public decimal RDFee { get; set; }
        public decimal ServiceFee { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
    }
}
