//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_BillingSub_Report
    {
        public Nullable<int> billingbatch { get; set; }
        public Nullable<int> accountid { get; set; }
        public string accountname { get; set; }
        public Nullable<decimal> loanamount { get; set; }
        public Nullable<decimal> rdfee { get; set; }
        public Nullable<decimal> rddocstamp { get; set; }
        public string facilitationfee { get; set; }
        public string mvis { get; set; }
        public string securedinformation { get; set; }
        public string rdexp { get; set; }
        public decimal servicefee { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> totalservicefee { get; set; }
        public string tctno { get; set; }
    }
}
