//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_Account
    {
        public int id { get; set; }
        public Nullable<int> batchreferenceid { get; set; }
        public Nullable<int> registryofdeedsid { get; set; }
        public string accountname { get; set; }
        public string tctno { get; set; }
        public Nullable<decimal> requestedrdfee { get; set; }
        public Nullable<decimal> rdfee { get; set; }
        public Nullable<decimal> gratuityfee { get; set; }
        public Nullable<decimal> loanamount { get; set; }
        public string rdorno { get; set; }
        public string epebno { get; set; }
        public Nullable<System.DateTime> dateofentry { get; set; }
        public Nullable<decimal> servicefee { get; set; }
        public Nullable<System.DateTime> datereleasedfromrd { get; set; }
        public Nullable<System.DateTime> datedelivered { get; set; }
        public Nullable<decimal> ctcgratuityfee { get; set; }
        public string ctcrdorno { get; set; }
        public Nullable<decimal> ctcrdfee { get; set; }
        public Nullable<System.DateTime> ctcdateofentry { get; set; }
        public string spardorno { get; set; }
        public Nullable<decimal> spardfee { get; set; }
        public Nullable<System.DateTime> spadateofentry { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> ctcstatusid { get; set; }
        public Nullable<bool> isprocessing { get; set; }
        public Nullable<bool> isprocessedctc { get; set; }
        public Nullable<bool> isprocessedspa { get; set; }
        public Nullable<bool> isreturn { get; set; }
    }
}
