//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_REM_MonthlyQuantityReport
    {
        public int id { get; set; }
        public string accountname { get; set; }
        public Nullable<int> registryofdeedsid { get; set; }
        public string RegistryOfDeedsName { get; set; }
        public decimal servicefee { get; set; }
        public Nullable<int> BankId { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
    }
}
