//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetAccess
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Access { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
