//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETCompany
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string PresentAddress { get; set; }
        public string ContactNumbers { get; set; }
        public string EmailAddress { get; set; }
        public string LogoLink { get; set; }
    }
}
