//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETRegistryOfDeed
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsInsideRegion { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public Nullable<int> EncodedById { get; set; }
        public Nullable<decimal> CMAmount { get; set; }
        public Nullable<decimal> REMAmount { get; set; }
        public Nullable<decimal> CMRDFeeAmount { get; set; }
        public Nullable<decimal> REMRDFeeAmount { get; set; }
        public Nullable<decimal> REMCTCAmount { get; set; }
    }
}
