//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUserAccessGroup
    {
        public int id { get; set; }
        public string description { get; set; }
        public string useraccess { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> dateencoded { get; set; }
        public Nullable<int> encodedbyid { get; set; }
        public string showincombobox { get; set; }
        public Nullable<bool> canedit { get; set; }
    }
}
