//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnAppraisal
    {
        public int Id { get; set; }
        public string BatchCode { get; set; }
        public string AccountName { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string CTCNo { get; set; }
        public Nullable<bool> WithVat { get; set; }
        public string TimeTable { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string PurposeOfAvailingServices { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsPrintedSOA { get; set; }
        public Nullable<int> NotedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string TotalProperty { get; set; }
    
        public virtual SetBankBranch SetBankBranch { get; set; }
        public virtual TxnAppraisalItem TxnAppraisalItem { get; set; }
        public virtual TxnAppraisalPaymentDetail TxnAppraisalPaymentDetail { get; set; }
        public virtual TxnAppraisalPaymentLog TxnAppraisalPaymentLog { get; set; }
        public virtual SetUser SetUser { get; set; }
        public virtual SetUser SetUser1 { get; set; }
    }
}
