//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnAppraisalItem
    {
        public int TnxAppraisalId { get; set; }
        public Nullable<int> RowNo { get; set; }
        public string ItemDescription { get; set; }
    
        public virtual TxnAppraisal TxnAppraisal { get; set; }
    }
}
