//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnAppraisalPaymentLog
    {
        public int TxnAppraisalId { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TxnAppraisal TxnAppraisal { get; set; }
    }
}
